In [ ]:
pip install ankr-sdk

In [ ]:
!pip install protobuf==4.21.9
!pip install google-cloud-vision
!pip freeze | grep protobuf

In [ ]:
!pip freeze | grep protobuf

In [ ]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
from ankr import AnkrWeb3

In [ ]:
ankr_w3 = AnkrWeb3()

block_list = []

for i in range(41799268,41799270):
    blocks = ankr_w3.query.get_blocks(
    blockchain="polygon",
    from_block=i,
    to_block=i,
    desc_order=True,
    include_logs=True,
    include_txs=True,
    decode_logs=True)
    
#start here    if
    
    df_1 = pd.DataFrame(blocks[0])
    df_1

    df_2 = pd.DataFrame(df_1[1][19])
    df_2

    logs_1 = pd.DataFrame(df_2[17].to_list())
    logs_1

    flat_list = [item for sublist in logs_1[1].tolist() for item in sublist]
    flat_list

    logs_2 = pd.DataFrame(flat_list)
    logs_2

    col1 = [tple[1] for tple in logs_2[[0,4,9]][0]]

    col2 = [tple[1] for tple in logs_2[[0,4,9]][4]]

    col3 = [tple[1] for tple in logs_2[[0,4,9]][9]]
    col3

    col4 = [tple.name for tple in col3]

    block_list.append({'pool address': col1,
                       'transaction hash': col2,
                       'method': col4})

block_list1 = pd.DataFrame(block_list)
block_list1

pool_address = [item for sublist in block_list1['pool address'] for item in sublist]
pool_address
txs_hash = [item for sublist in block_list1['transaction hash'] for item in sublist]
txs_hash
method = [item for sublist in block_list1['method'] for item in sublist]
method

log = pd.DataFrame({'pool address': pool_address,
                    'transaction hash': txs_hash,
                    'method': method})
log

swap = log[log.method.str.contains('Swap')]
swap

,pool address,transaction hash,method
4,0x56b8936a96cd5ee5c5837f385a19b4c2999fd74a,0xc53c8406160591b583d092de899f9b59ae9b79603146...,Swap
218,0x604229c960e5cacf2aaeac8be68ac07ba9df81c3,0x238b0a91716d93b147a8b2adccb6276b40a49ac6a183...,Swap
221,0x3cae7d8bd8c20d0ae2faf738f8d4b0fb02ac7947,0x238b0a91716d93b147a8b2adccb6276b40a49ac6a183...,Swap
319,0x019ba0325f1988213d448b3472fa1cf8d07618d7,0x80d9ec4300ba876b0b8ff45d7eb66d677b20742ccc61...,Swap
325,0x1f1e4c845183ef6d50e9609f16f6f9cae43bc9cb,0xebd1faf52216e8451ac8059b04d1486b06316162c851...,Swap
328,0x019ba0325f1988213d448b3472fa1cf8d07618d7,0xebd1faf52216e8451ac8059b04d1486b06316162c851...,Swap
331,0x6e7a5fafcec6bb1e78bae2a1f0b612012bf14827,0xebd1faf52216e8451ac8059b04d1486b06316162c851...,Swap
339,0x019ba0325f1988213d448b3472fa1cf8d07618d7,0x3354bd8d0eaab85eb78ba4a57937aa8714930357331e...,Swap
354,0x1bd06b96dd42ada85fdd0795f3b4a79db914add5,0x3354bd8d0eaab85eb78ba4a57937aa8714930357331e...,Swap
367,0xc4e595acdd7d12fec385e5da5d43160e8a0bac0e,0xc91f5aa8011e652b927cc6d3383d8ed478eb7b825de4...,Swap
370,0x1bd06b96dd42ada85fdd0795f3b4a79db914add5,0xc91f5aa8011e652b927cc6d3383d8ed478eb7b825de4...,Swap
372,0x019ba0325f1988213d448b3472fa1cf8d07618d7,0xc91f5aa8011e652b927cc6d3383d8ed478eb7b825de4...,Swap
422,0x019ba0325f1988213d448b3472fa1cf8d07618d7,0xd2ef6eb2dd85c57dc4c34286d43929c56022b2539b7f...,Swap
436,0x9b5c71936670e9f1f36e63f03384de7e06e60d2a,0x9d5224c5dbfc9871fc4db3fea3812cc29a77d7f541e5...,Swap
439,0xe88e24f49338f974b528ace10350ac4576c5c8a1,0x9d5224c5dbfc9871fc4db3fea3812cc29a77d7f541e5...,Swap
442,0x019ba0325f1988213d448b3472fa1cf8d07618d7,0x9d5224c5dbfc9871fc4db3fea3812cc29a77d7f541e5...,Swap
710,0x56b8936a96cd5ee5c5837f385a19b4c2999fd74a,0xa6a4de6f16f1ba04f9aefa23364d06cb4e6095628642...,Swap